### PR TITLE
XMR chart's inclusion and integration into the existing code 

### LINKED ISSUE #101: Add individuals chart functionality to the package
Enable use of I-charts (individuals charts) in autospc. This is a sub-issue of #75.

### PR DESCRIPTION
**Pull request by Comfortti**
Hi @HorridTom could you please have a look at this?

### CODE REVIEW

**Comment by HorridTom** [comment]
[This](https://github.com/HorridTom/autospc/blob/09ca25c3f4d8d68c38d7a75f55dd012e4e7813e7/R/plot_code.R#L93-L101) code provides functionality to guess what chart type a user needs based on the columns specified in the arguments to `plot_auto_SPC`. This is going to become difficult or even impossible to do as we broaden the available chart types. Since this is really a "nice to have" rather than a core functionality of the package, I suggest we deprecate this functionality.

The `lifecycle` package, and in particular the [`deprecate_warn()`](https://lifecycle.r-lib.org/reference/deprecate_soft.html) function, provides deprecation support and we should probably use that to do this.

**Comment by Comfortti** [comment]
Hi @HorridTom
Could you please have a look at these commits?
I've also modified the pull request name so that it makes more sense.

**Comment by HorridTom** [comment]
Hi @Comfortti - I think I've fixed that issue with the warning for calculation-period-only charts. See the last two commits I pushed. If you could pull down to your repo and check all the tests pass for you too that would be great. We could meet tomorrow too if you're available to discuss.

**Comment by Comfortti** [comment]
> Hi @HorridTom 
I've pulled the latest commits, ran the tests and run the autospc package on the test_e2e_data dataset.
All is working perfectly on my end too

I should be pushing the comments on how the correct_answer_I.rds was produced shortly.

**Pull request merged**
