### PR TITLE
Bugfix linetype 59

### LINKED ISSUE #59: Issue with merged branch for plot aesthetics
Hi @HorridTom, my fault for not checking enough cases. I installed the latest version of the package and got this:
image

I'll make a new branch now to fix.

### PR DESCRIPTION
**Pull request by HorridTom**
Fixes #59 

@ImogenConnorHelleur please could you check i) that this works for you and ii) that you're happy with the approach?

Slightly weirdly, I couldn't actually reproduce the problem when reverting back to master... Not sure why that is! But in any case, I think this sorts the legend out, and I've added a test to check the linetypes are correctly created.

### CODE REVIEW

**Comment by HorridTom** [comment]
Ok the bug did **not** manifest with the package versions as per commit a147516 and earlier; it **does** manifest after updating all packages (commit de48c48). So this I think explains why it is happening on installing autospc into a new repo - on installation, some dependency package is being installed with the latest version. So the solution needs to be to identify how to fix this _with_ the updated versions - there's no point in having our package insist on an older version!

So now, I can reproduce the bug in the package development environment (not just on installation into a separate repo) *and* the bug is captured by the tests (3 failing). So this should now be a better position from which to fix the bug...

**Comment by HorridTom** [comment]
Ok @ImogenConnorHelleur I think this is now fixed. I now get the correct linetypes and legend both within the development environment and when installing the package in a clean repo. I have not tested this under a wide range of conditions - just for `test_data.rda`. I don't quite know what will happen if e.g. there are two calculation periods consecutively (which can happen). Wondering whether you could look at this on Monday?

**Comment by HorridTom** [comment]
@ImogenConnorHelleur I'm going to merge this before making the final version of the slides for tomorrow, we can further test afterwards as this branch does fix the original issue.

**Comment by ImogenConnorHelleur** [comment]
> Ok @ImogenConnorHelleur I think this is now fixed. I now get the correct linetypes and legend both within the development environment and when installing the package in a clean repo. I have not tested this under a wide range of conditions - just for `test_data.rda`. I don't quite know what will happen if e.g. there are two calculation periods consecutively (which can happen). Wondering whether you could look at this on Monday?

Hi @HorridTom , I have tested this with data with consecutive calculation periods and it works fine.

**Comment by HorridTom** [comment]
Ah wonderful, thanks @ImogenConnorHelleur - I'll merge first thing tomorrow

**Pull request merged**
